"use client"
import { ThemeProvider } from "@/components/theme-provider"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'





const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
    
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div>
           
            </div>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}